@startuml Вход в личный кабинет
    autonumber

    actor Пользователь

    participant Frontend
    participant Сервер
    participant БазаДанных

    activate Пользователь
        Пользователь -> Frontend: выбрать "Войти"

    activate Frontend
        Frontend -> Frontend: отображение экрана идентификации по номеру
        Пользователь -> Frontend: Ввод номера телефона
        Frontend -> Frontend: активация кнопки "получить код подтверждения"
        Пользователь -> Frontend: нажать на кнопку "получить код подтверждения"

    activate Сервер
        Frontend -> Сервер: номер телефона пользователя
        Frontend -> Frontend: отображение поля "код подтверждения"
        Сервер -> Сервер: обработка телефона пользователя
        Сервер -> Сервер: звонок на номер телефона пользователя
        Пользователь -> Frontend: ввод кода подтверждения
        Frontend -> Сервер: код подтверждения
        Сервер -> Сервер: проверка данных на валидацию

    alt данные не прошли валидацию
        Сервер -> Сервер: отправка смс на телефон пользователя
        Пользователь -> Frontend: ввод кода подтверждения
        Frontend -> Сервер: код подтверждения
        Сервер -> Сервер: проверка данных на валидацию

    else данные прошли валидацию
    activate БазаДанных
        Сервер -> БазаДанных: поиск учетной записи по номеру телефона

        alt учетная запись уже есть
        БазаДанных --> Сервер: учетная запись найдена
        Сервер -> БазаДанных: запрос информации о пользователе
        БазаДанных --> Сервер: информация для отображения в ЛК

        Сервер --> Frontend: пользователь авторизован

        else учетной записи нет
            Сервер -> БазаДанных: внесение информации о новом пользователе
            deactivate БазаДанных
            Frontend -> Frontend: отображение окна опроса (пол)
            Пользователь -> Frontend: выбор пола
            deactivate Сервер
        end
            Frontend -> Frontend: отображение окна ЛК
            Frontend --> Пользователь: вход в ЛК успешно завершен
    end  
    deactivate Frontend
    deactivate Пользователь
@enduml